export const BASE_URL = "https://api.themoviedb.org/3/"
export const IMAGE_BASE_URL = "https://image.tmdb.org/t/p/w500"
export const POPULAR_URL = "movie/popular"
export const TOP_RATED_URL = "movie/top_rated"
export const UPCOMING_URL = "movie/upcoming"
export const NOW_PLAYING = "movie/now_playing"
export const MOVIE_DETAIL_URL ="movie/"
export const SEARCH_MOVIE_URL ="search/movie"
